name: Generate APK
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload APK to Github Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app_debug
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error

  upload-app-distribution:
    name: "Upload APK to Firebase App Distribution"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Download Stored Artifact
        uses: actions/download-artifact@v3
        with:
          name: app_debug

      - name: Upload APK
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          # Acquire from Firebase Console. Project Overview -> Project Settigns -> Under the App area you will see `App ID`
          appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          # Generate using Firebase CLI. Command to run `firebase login:ci`.
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers # Speciy a group you want the app to be distributed to
          file: app_debug.apk
